<?xml version="1.0" encoding="utf-8"?><Database Name="TechSupport" Class="TechSupportDB_LINQ2SQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=den1.mssql8.gear.host;Initial Catalog=techsupport1;User ID=techsupport1" SettingsObjectName="SportsProUserInterfaceLayer.Properties.Settings" SettingsPropertyName="TechSupportConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="ZipCode" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Customer_Incident" Member="Incidents" ThisKey="CustomerID" OtherKey="CustomerID" Type="Incident" />
      <Association Name="Customer_Registration" Member="Registrations" ThisKey="CustomerID" OtherKey="CustomerID" Type="Registration" />
      <Association Name="State_Customer" Member="State1" ThisKey="State" OtherKey="StateCode" Type="State" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Incidents" Member="Incidents">
    <Type Name="Incident">
      <Column Name="IncidentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TechID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateOpened" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateClosed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Incident" Member="Customer" ThisKey="CustomerID" OtherKey="CustomerID" Type="Customer" IsForeignKey="true" />
      <Association Name="Product_Incident" Member="Product" ThisKey="ProductCode" OtherKey="ProductCode" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Technician_Incident" Member="Technician" ThisKey="TechID" OtherKey="TechID" Type="Technician" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ProductCode" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Version" Type="System.Decimal" DbType="Decimal(18,1) NOT NULL" CanBeNull="false" />
      <Column Name="ReleaseDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Product_Incident" Member="Incidents" ThisKey="ProductCode" OtherKey="ProductCode" Type="Incident" />
      <Association Name="Product_Registration" Member="Registrations" ThisKey="ProductCode" OtherKey="ProductCode" Type="Registration" />
    </Type>
  </Table>
  <Table Name="dbo.Registrations" Member="Registrations">
    <Type Name="Registration">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RegistrationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Registration" Member="Customer" ThisKey="CustomerID" OtherKey="CustomerID" Type="Customer" IsForeignKey="true" />
      <Association Name="Product_Registration" Member="Product" ThisKey="ProductCode" OtherKey="ProductCode" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.States" Member="States">
    <Type Name="State">
      <Column Name="StateCode" Type="System.String" DbType="Char(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="FirstZipCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastZipCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="State_Customer" Member="Customers" ThisKey="StateCode" OtherKey="State" Type="Customer" />
    </Type>
  </Table>
  <Table Name="dbo.Technicians" Member="Technicians">
    <Type Name="Technician">
      <Column Name="TechID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Technician_Incident" Member="Incidents" ThisKey="TechID" OtherKey="TechID" Type="Incident" />
    </Type>
  </Table>
</Database>